import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'ar', 'ru', 'es', 'fr', 'sw', 'id', 'it'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? arText = '',
    String? ruText = '',
    String? esText = '',
    String? frText = '',
    String? swText = '',
    String? idText = '',
    String? itText = '',
  }) =>
      [
        enText,
        arText,
        ruText,
        esText,
        frText,
        swText,
        idText,
        itText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // CreateAccount3
  {
    'dji0umup': {
      'en': 'Login',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'xdpvk87y': {
      'en': 'Email',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'hkklj7l6': {
      'en': 'password',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'kalktcaf': {
      'en': 'sign in',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ghmcah99': {
      'en': 'forgot password',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '661q62u8': {
      'en': 'Continue without account',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'vjn7n7h4': {
      'en': 'Welcome',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'a28b8ph3': {
      'en': 'Sign up',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'szna0cgp': {
      'en': 'Create acount',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'zvfj6ex5': {
      'en': 'Email',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '7ciy7mzf': {
      'en': 'password',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '297y0jg3': {
      'en': 'sign up',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'no7229yj': {
      'en': 'By continuing you agree to the \nfollowing terms and conditions',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'u6rvmqyd': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
  // CreateAccount3CopyCopy
  {
    'wksrc1q4': {
      'en': 'Gemini big',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'u81dkswp': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'mdtk6ew3': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '6nsnzfxi': {
      'en': 'Gemini 2.0 Flash',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'vei3qh5o': {
      'en': 'gemini 2.5 pro',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ot0czlyv': {
      'en': 'Gemini big',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'dxsnluii': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'kq112q55': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ictqx96c': {
      'en': 'gpt-4o',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'x5nwlu4j': {
      'en': 'gpt-4o-mini',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'mb3caj2n': {
      'en': 'gpt-4.5-preview',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '9vahmh2d': {
      'en': 'o1',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '53sje947': {
      'en': 'o3-mini',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'dvnt8tpx': {
      'en': 'Gemini big',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'iczy3yyx': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'fp8d9pw1': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'vyw54u1b': {
      'en': 'Claude 3.5 Sonnet',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '8wd9ioby': {
      'en': 'Claude 3 Opus',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'hqfnsrld': {
      'en': 'Claude 3.5 Haiku',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'f5szo1f0': {
      'en': 'Claude 3.7 Sonnet',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'zdicwsed': {
      'en': 'L O G O U T',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ixcijlbk': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '5mk35unn': {
      'en': 'input task',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'sq9329ap': {
      'en': 'NEW CHAT',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'p3yhdtdm': {
      'en': 'MODELS',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'zg5tsxp9': {
      'en': 'Gemini big',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '8ygzo45j': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ehj9478e': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'bqu5p6mf': {
      'en': 'gemini-1.5-pro',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'chx6z2sp': {
      'en': '\tgemini-1.0-pro',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'broit8zz': {
      'en': 'Gemini 2.0 Flash',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    't7g5lao6': {
      'en': 'Gemini 2.0 Pro',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'lalnhxr5': {
      'en': 'gemini-1.5-flash',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'zsidwmak': {
      'en': 'gemini-2.5-pro-exp-03-25',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ven4wqou': {
      'en': 'Gemini big',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'n06s8t4y': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'z28rhbs2': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'nd28k1ht': {
      'en': 'gpt-4o',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'k70x1tuj': {
      'en': 'gpt-4o-mini',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'xljrd96d': {
      'en': 'gpt-4.5-preview',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'sx4bh1ht': {
      'en': 'o1',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'q6o5q5ps': {
      'en': 'o3-mini',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '1cwuuied': {
      'en': 'Gemini big',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ymc87s58': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'nkci2jzy': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '1sg1s620': {
      'en': 'Claude 3.5 Sonnet',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '3ehd1ij4': {
      'en': 'Claude 3 Opus',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'lz47ld8x': {
      'en': 'Claude 3.5 Haiku',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'fixtkt6k': {
      'en': 'Claude 3.7 Sonnet',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'cdjvhwzq': {
      'en': 'Clear',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '7cj1yd91': {
      'en': 'L O G O U T',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'b5ufgcke': {
      'en': 'NEW CHAT',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '2pe6ctpx': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
  // terms
  {
    'kk2pf4jf': {
      'en': 'exit',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
  // anymonous
  {
    'wh6blffz': {
      'en':
          'Please sign in using your acount to get acces to all of our features. Terms of service continue to apply.',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '3xqltemh': {
      'en': 'Cancel',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '1peti8by': {
      'en': 'continue',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
  // info
  {
    'ebyaqg0u': {
      'en':
          'It apears that you have not filled out your payment details this is required for you to continue you will not be charged. Please fill them out here ',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'lb6vjxaj': {
      'en': 'here',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'd204qkjc': {
      'en': 'models',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
  // infos
  {
    'i5wmddw8': {
      'en':
          'Please fill out your payment details for authentication purposes note no fee will be incurred and you will only be charged for usage. Fill them out here',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '3b6m3c1f': {
      'en': ' here',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ffukz0tz': {
      'en': 'Cancel',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
  // Miscellaneous
  {
    '2qwwyize': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '3vbttn68': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'g1dolwal': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'huuv3lmq': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '6np4gwm3': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '12l5morf': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'def8uhwu': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ip0bhb1h': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '4lcq7tc9': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'j6e6usvl': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'q0yse0ex': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'lk4rie4m': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '7dddrn89': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'pz5a6uxj': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'vcif2f3o': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '1t7cnxpm': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    '06fshlqt': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'd6x7mf53': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'tpajmxjd': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ri4t0dkw': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'spg9y2sy': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'hueopjv2': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'faf3exel': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'dj5gd1no': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'ywnkeuj7': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'c3w0ijsu': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'a1qkof5q': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
    'zinjp9ox': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'id': '',
      'it': '',
      'ru': '',
      'sw': '',
    },
  },
].reduce((a, b) => a..addAll(b));
